### ISSUE TITLE
Dead Link - Documentation

### ISSUE THREAD

**Issue by jonwilks** [salesforce/policy_sentry#108]
Line #57 of README.md has a dead link.

Link Text: the ...AWS documentation on **Actions, Resources, and Condition Keys** documentation...
Link Address: https://github.com/salesforce/policy_sentry/blob/master/1

**Comment by kmcquade** [comment]
It's not, actually :) https://www.markdownguide.org/basic-syntax/#reference-style-links 

Were you using https://github.com/tcort/markdown-link-check or another linter? I could probably get rid of the reference style links to make the linters happy

**Comment by jonwilks** [comment]
Hmm, just browsing it via Chrome. Threw a 404, consistently . 

Not a big deal, likely something funky on my end. Please close if you see fit.

**Comment by mbeacom** [comment]
@jonwilks @kmcquade The ref was bad at https://github.com/salesforce/policy_sentry/blame/master/README.md#L57

I have updated the ref in #109

**Comment by kmcquade** [comment]
Weird. Okay!

By the way, @jonwilks @mbeacom - a few small PRs have been popping up in the last 24 hours. I'm wondering what piqued your interest, if there is a particular user group or company trying to test it, etc. Mind sharing? I can also be reached via the Gitter for this repo, Keybase, or Twitter.

**Comment by jonwilks** [comment]
@kmcquade I saw it on /r/aws. Very relevant to my current project.

**Comment by mbeacom** [comment]
@kmcquade Your repo came up in my Github explore repositories feed.  Fairly relevant for me as well!

**Comment by kmcquade** [comment]
Right on. Well, let me know if you need anything or have any questions :)
