### ISSUE TITLE
YAML Output?

### ISSUE THREAD

**Issue by salt-mountain** [salesforce/policy_sentry#11]
Is it possible to have the generated output be given in YAML format?

**Comment by kmcquade** [comment]
@salt-mountain for what purpose? CloudFormation? 

If you are just looking for a direct YML representation of the JSON policy as-is, you can use [yq](https://github.com/mikefarah/yq/):

```bash
yq r examples/output-dir/policy-puma.json
```

**Comment by salt-mountain** [comment]
Yeah. I was just wondering if there was a way to specify / set the default output of `policy_sentry write-policy` to YAML without having to use another program/tool.

**Comment by kmcquade** [comment]
Not at this point. But PRs are very welcome!

**Comment by kmcquade** [comment]
@salt-mountain - I'm just now revisiting this. What would you want the output to look like for CloudFormation? I am not well-versed in CF so I'd like to hear your desired format.

**Comment by salt-mountain** [comment]
@kmcquade sorry for the late response.

I don’t think there’s really a stylistic preference, just valid YAML. YAML is just much easier to read when you’re looking at large CloudFormation files. Anything that can convert JSON to YAML usually does the trick and I’ve had to do that before in the past. 

I’m not sure if that helps at all, but let me know if I can help further or assist in any way.
