### ISSUE TITLE
'redshift:getclustercredentials' is returned as a "Permissions management" action

### ISSUE THREAD

**Issue by 0xdabbad00** [salesforce/policy_sentry#132]
When running the following:
```
get_actions_with_access_level(db_session, "all", "Permissions management")
```

The action `redshift:getclustercredentials` is returned, which I do not think is correct.

**Comment by kmcquade** [comment]
There was a time where I did an override on the access levels, and decided to put "Permissions management" on the calls that return credentials. I have been thinking for a while that this is probably not the best move.

Think I should revert it?

For reference - the overrides file is here: https://github.com/salesforce/policy_sentry/blob/master/policy_sentry/shared/data/access-level-overrides.yml

And the credentials exposure file is here:
https://github.com/salesforce/policy_sentry/blob/master/policy_sentry/shared/data/audit/credentials-exposure.txt

**Comment by 0xdabbad00** [comment]
It was unexpected to me.  I expected the "Permissions management" actions to be one that's changed resource policies, and not ones that return credentials.  This is your call though.  I'm merging in the community auditors now to Palriament and noticed it.
