### ISSUE TITLE
Feature: process Actions that have same name but different ResourceTypeName

### ISSUE THREAD

**Issue by lvincel** [salesforce/policy_sentry#159]
Wildcard-only-bulk-selection does not include entries when ActionTable looks like this:

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| id  | service     | name                   | access_level | resource_type_name | resource_type_name_append_wildcard | resource_arn_format                                                                                                     |
| --- | ----------- | ---------------------- | ------------ | ------------------ | ---------------------------------- | ----------------------------------------------------------------------------------------------------------------------- |
| 589 | autoscaling | CreateAutoScalingGroup | Write        | autoScalingGroup   | True                               | arn:${Partition}:autoscaling:${Region}:${Account}:autoScalingGroup:${GroupId}:autoScalingGroupName/${GroupFriendlyName} |
| 590 | autoscaling | CreateAutoScalingGroup | Write        | None               | False                              | *                                                                                                                       |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

It is a pain to find them all out when there's many actions and many services to add in a policy. Generating those somewhere, even commented, either as if they were put in single-action or in the bulk section, could save a great amount of time.

**Comment by kmcquade** [comment]
> Wildcard-only-bulk-selection does not include entries when ActionTable looks like [see above]:

@lvincel that is by design. The wildcard-only bulk selection is meant to identify IAM Actions that do not support resource ARN constraints.

I think the "override" capability that you are looking for is `skip-resource-constraints`.

Example: https://policy-sentry.readthedocs.io/en/latest/user-guide/writing-policies/crud-examples.html#example-2-skipping-resource-constraints

**Comment by kmcquade** [comment]
@lvincel Are you looking for something like this?

#### Input

```yaml
mode: crud
write:
- 'arn:${Partition}:autoscaling:${Region}:${Account}:autoScalingGroup:${GroupId}:autoScalingGroupName/${GroupFriendlyName}'
```

#### Output

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AutoscalingWriteAutoscalinggroup",
            "Effect": "Allow",
            "Action": [
                "autoscaling:AttachInstances",
                "autoscaling:AttachLoadBalancerTargetGroups",
                "autoscaling:AttachLoadBalancers",
                "autoscaling:BatchDeleteScheduledAction",
                "autoscaling:BatchPutScheduledUpdateGroupAction",
                "autoscaling:CompleteLifecycleAction",
                "autoscaling:CreateAutoScalingGroup",
                "autoscaling:DeleteAutoScalingGroup",
                "autoscaling:DeleteLifecycleHook",
                "autoscaling:DeleteNotificationConfiguration",
                "autoscaling:DeletePolicy",
                "autoscaling:DeleteScheduledAction",
                "autoscaling:DetachInstances",
                "autoscaling:DetachLoadBalancerTargetGroups",
                "autoscaling:DetachLoadBalancers",
                "autoscaling:DisableMetricsCollection",
                "autoscaling:EnableMetricsCollection",
                "autoscaling:EnterStandby",
                "autoscaling:ExecutePolicy",
                "autoscaling:ExitStandby",
                "autoscaling:PutLifecycleHook",
                "autoscaling:PutNotificationConfiguration",
                "autoscaling:PutScalingPolicy",
                "autoscaling:PutScheduledUpdateGroupAction",
                "autoscaling:RecordLifecycleActionHeartbeat",
                "autoscaling:ResumeProcesses",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:SetInstanceHealth",
                "autoscaling:SetInstanceProtection",
                "autoscaling:SuspendProcesses",
                "autoscaling:TerminateInstanceInAutoScalingGroup",
                "autoscaling:UpdateAutoScalingGroup"
            ],
            "Resource": [
                "arn:${Partition}:autoscaling:${Region}:${Account}:autoScalingGroup:${GroupId}:autoScalingGroupName/${GroupFriendlyName}"
            ]
        }
    ]
}
```

#### Potentially...

Instead of the output shown above, are you looking for the ability to get those same exact actions, but override it to `*` in the Resource block? Like below.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AutoscalingWriteAutoscalinggroup",
            "Effect": "Allow",
            "Action": [
                "autoscaling:AttachInstances",
                "...",
                "autoscaling:UpdateAutoScalingGroup"
            ],
            "Resource": [
                "arn:${Partition}:autoscaling:${Region}:${Account}:autoScalingGroup:${GroupId}:autoScalingGroupName/${GroupFriendlyName}"
            ]
        }
    ]
}
```

**Comment by lvincel** [comment]
I see now, I did not test this with placeholders, and I was trying to find a way to generate policies with "create" actions when the arn includes the ID that cannot be known beforehand. I tried with '*' but it was not working.
This deserves a place in the docs !

Thanks again.
