### ISSUE TITLE
Create Reference Policy repository for copypasta

### ISSUE THREAD

**Issue by kmcquade** [salesforce/policy_sentry#183]
This would be really useful for users who are getting the hang of this.

**Comment by brianelliott-wt** [comment]
Hey @kmcquade are there any specific policy reference docs you need help creating?  I might be able to help generate a few.  I know it would've been helpful for me when starting to use this.

**Comment by kmcquade** [comment]
Hey @brianelliott-wt. I had two basic ideas:
- Secure versions of IAM policies provided via AWS tutorials
- Based on experience and knowledge of common scenarios

At the end of the day - I think the most helpful thing for users is to have many helpful examples, not just one example per feature (which is pretty much what we have today in the documentation). 

The documentation (which was recently reformatted, by the way) has gotten better, and I've made sure to provide examples as we've added new features. See the example pages from [the documentation](https://policy-sentry.readthedocs.io/en/latest/) indicated below.

![image](https://user-images.githubusercontent.com/3422255/82505560-0a000200-9acc-11ea-81a2-1fb630288c78.png)

Do you think it would bee helpful to have a separate subsection in the Policy docs that would show before/after? Or something else?

I'm very open to your opinion on this as a user.

**Comment by kmcquade** [comment]
I also have a good amount of YML files that I used for my unit tests that are in this folder: https://github.com/salesforce/policy_sentry/tree/master/examples/yml. Some of them might be useful

**Comment by brianelliott-wt** [comment]
Thanks for pointing out the examples docs, I did references those a few times to try and figure out how to use the tool a little while ago.

The new docs are great, I had not actually read through them yet.  The examples mixed into the types of policies you can write feels a little crowded and I felt a little lost going through each of them in a row.  Maybe its worth have an example sub-section at the end of the "Writing Policies" section like you have for "Wildcard-only"?

There are also some features that have an example page but no normal info page, like "Skipping Resource Constraints" and "Excluding Actions"

**Comment by kmcquade** [comment]
That makes sense. All of this is very helpful. What do you think about this hierarchy?

* **Writing policies**
  - CRUD Mode
  - Wildcard-only
  - Skipping Resource Constraints
  - Excluding Actions
  - Minimizing Characters
  - Actions Mode
  - **Examples**
    * Feature examples
      - Basic CRUD
      - Skipping Resource Constraints
      - Excluding Actions
      - Wildcard-only
    * AWS Service-specific examples
      - EC2
      - IAM
      - KMS
      - RDS
      - S3
      - Secrets Manager
      - SSM Parameter Store


Or is that too cluttered as well?

**Comment by kmcquade** [comment]
BTW - Mkdocs (current Docs format) is nicer to use than the last one... the table of contents configuration is here: https://github.com/salesforce/policy_sentry/blob/master/mkdocs.yml.

**Comment by brianelliott-wt** [comment]
I think that hierarchy looks a lot better 👍

**Comment by kmcquade** [comment]
Awesome. I’ll go ahead and do that. Thanks for your input!

**Comment by kmcquade** [comment]
I am closing this issue because it's stale AF
