### ISSUE TITLE
Update docs on Contributing to Documentation - previous sphinx-related content is still there

### ISSUE THREAD

**Issue by L-E-iT** [salesforce/policy_sentry#188]
https://policy-sentry.readthedocs.io/en/latest/contributing/documentation/

According to these docs there should be a make file in the docs/ folder that I assume was generated in the sphinx-quickstart generation for the docs. Either way, the make file doesn't seem to be in the repo and there are not instructions to generate a new one aside from following the sphinx-quickstart guide, which I don't believe is the right action.

I was looking to put in the formatting fix from #183 but I'm not able to generate the docs on my machine, according to the documentation, without that make file.

**Comment by kmcquade** [comment]
Hey, thanks for opening. You’re correct - the Makefile was used when we still used Sphinx for the documentation. We use Mkdocs Material now. The documentation build commands are available with the `invoke` command, and all of those commands are viewable within the tasks.py file.

If you’re not familiar with PyInvoke, try this:

```bash
pipenv install —dev
invoke -l
```

And you’ll see the commands for the docs. I can’t remember the commands off the top of my head (typing from my phone), but I believe it’s `invoke docs.build-docs` and `invoke docs.serve-docs`

**Comment by L-E-iT** [comment]
Thanks! That did it.  

`pipenv install --dev` followed by `invoke docs.builds-docs` and `invoke docs.serve-docs`

**Comment by L-E-iT** [comment]
I think this can be closed. It looks to be fixed by #181

**Comment by kmcquade** [comment]
Yep! Thanks @L-E-iT
