### ISSUE TITLE
Policy Sentry for GCP or Azure?

### ISSUE THREAD

**Issue by satendragaundar** [salesforce/policy_sentry#214]
Can this be used on GCP or Azure or is Policy Sentry tailored for AWS only. Many Thanks

**Comment by kmcquade** [comment]
It's only for AWS. The philosophy of limiting access based on resources and access levels, leveraging data scraped from the documentation, can certainly be applied for GCP, Azure, or AliCloud - but that's not within the scope of this tool.

**Comment by satendragaundar** [comment]
Ok Thanks. I sure can see benefits of this on the other platforms too but thank you for the tool even though i was hoping you would say yes to GCP :-) ...
