### ISSUE TITLE
Missing condition keys for s3 

### ISSUE THREAD

**Issue by jsmartin** [salesforce/policy_sentry#225]
Was doing some investigative work on condition keys for s3:

The following returns nothing:

```policy_sentry query condition-table --service s3```

but according to [the docs](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazons3.html), it should return many.

This is version 0.8.7 and after having done a ```policy_sentry initialize --fetch --build```

**Comment by kmcquade** [comment]
Thanks @jsmartin ! You managed to uncover a bug that affected **all** `policy_sentry query condition-table --service service_prefix` queries 😅. Merging the fix shortly.
