### ISSUE TITLE
Create UI for Policy Sentry

### ISSUE THREAD

**Issue by kmcquade** [salesforce/policy_sentry#236]
A lot of users have requested a UI for Policy Sentry. Here's what I think this would take:

* [FastAPI](https://fastapi.tiangolo.com/)
* Serverless framework to deploy it in AWS as a Lambda function with API Gateway
* VueJS frontend that simply calls the REST API

If anyone is interested in helping out or collaborating, please ping me.

**Comment by reetasingh** [comment]
@kmcquade I am interested

**Comment by kmcquade** [comment]
@reetasingh cool! Do you want to try setting up the Lambda function?

Feel free to DM me over Twitter or ping me over the Gitter channel to discuss.

**Comment by rohanshenoy96** [comment]
Hi @kmcquade. I would like to help with this. If it's still open please let me know

**Comment by kmcquade** [comment]
@rohanshenoy96 you work at Salesforce, right? Do you go by another name in our systems? I tried to find you over slack but couldn't find you. I can ping you directly over there

**Comment by rohanshenoy96** [comment]
Not on slack with salesforce email yet. Currently in Vlocity email. I pinged you on hangout from rshenoy@salesforce.com.

**Comment by kmcquade** [comment]
I am going to close this. It will be a more appropriate issue in the new repository
