### ISSUE TITLE
[Discussion] Replace nose with pytest

### ISSUE THREAD

**Issue by mattyjones** [salesforce/policy_sentry#25]
According to the [docs](https://nose.readthedocs.io/en/latest/) nose has been unmaintained for some time now. The suggestions are [nose2](https://github.com/nose-devs/nose2) and [pytest](http://pytest.org/en/latest/). I have no real reason for choosing pytest other than my preference but I am open to suggestions and discussions on this.

@kmcquade

**Comment by kmcquade** [comment]
Probably a good idea given that it's not maintained anymore.

If you're willing to take that on, it sounds good to me.

**Comment by kmcquade** [comment]
Note: I added this to invoke and validated that the old nose tests work here with pytest. Just need to update Travis to use pytest and then we can close this issue.
