### ISSUE TITLE
Version 0.9.0 Breaking Changes Documentation

### ISSUE THREAD

**Issue by brianelliott-wt** [salesforce/policy_sentry#251]
According to the release notes Version 0.9.0 has some breaking changes depending on if you `iam-definitions.json` file was generated in a previous version.

It might be best to include some notes in the documentation about this update and the fix for it (I just moved the .policy_sentry folder in my home directory and let the tool create a new one. I'm not sure what the best practice here is though).

I can find a place in the docs for it and submit a PR if a best practice is decided on. This stumped me for a bit after accidentally updating and then finding out what the cause was from the release notes.  I only knew where to look because of a previous issue I submitted where the location of the `iam-definition.json` cache was mentioned.

**Comment by kmcquade** [comment]
Ah! Yes we should definitely put that in the docs. I would gladly welcome a PR. I think having this issue opened will help too :)

I try to mark any breaking changes in the Changelog, but I can't recall if I did that for 0.9.0. Perhaps we can highlight breaking changes in the Changelog with an emoji, like ‼️  (`:bangbang:`) so it is easy to eyeball those breaking changes when scrolling through the Changelog. What do you think about that?

Btw - I do make sure to increment a new minor version anytime there are breaking changes, btw. I don't anticipate any more changes to the `iam-definitions.json` file structure, but if we did, then I would definitely move it to 0.10.0 or whatever the next minor version number would be.

**Comment by brianelliott-wt** [comment]
I think a ‼️ works, but if it could be something that stands out a bit more like a 💥 that might help.

As far as where the docs should hold breaking changes and solutions to those, or where to store fixes to common problems, would you expect that to be found in the `appendices` section or in a new section all together?

**Comment by brianelliott-wt** [comment]
I should add, ‼️ showed up different before for me and was not as noticeable. I was on my desktop at the time so it could've just been a different emoji that didn't stand out as much as it does on my mac? 🤔

**Comment by kmcquade** [comment]
> As far as where the docs should hold breaking changes and solutions to those, or where to store fixes to common problems, would you expect that to be found in the appendices section or in a new section all together?

In the "Contributing" section :) 

I like the 💥 :D

**Comment by kmcquade** [comment]
@brianelliott-wt - by the way, since I know you make use of this library...

https://github.com/salesforce/policy_sentry/pull/261

@reetasingh's PR above changes a method or two. She has some really solid comments that explain it. Just wanted to make sure that removing the methods in that library won't break you... let me know.

**Comment by brianelliott-wt** [comment]
Not sure if you want me commenting on that PR or not, but those changes look great. They make sense.

**Comment by kmcquade** [comment]
Fantastic :) 

No need to comment on the PR, just thought I'd ask.
