### ISSUE TITLE
Missing resource types in the AWS docs (and policy_sentry)

### ISSUE THREAD

**Issue by jsmartin** [salesforce/policy_sentry#272]
I've noticed there are quite a few actions that don't have associated resource types when I would assume they would.   For example, ec2:AttachNetworkInterface -- you would think would be associated with an ec2 instance and/or elastic interface, but it is not in the dos (and thus  not in policy_sentry) I know this is not a policy_sentry bug since it is just using the AWS docs page, but it seems there should be some way to override what the docs are saying similar to the override behavior that currently exists for actions.  Am I missing something fundamental as to why AWS would not state this in their docs?

**Comment by kmcquade** [comment]
I have no idea why AWS would not have their docs accurately representing which actions can be restricted using resource ARNs. There was a point where the docs said that `secretsmanager:CreateSecret` supported resource ARN restrictions, and then changed it so that it didn't, and then changed it back.

**Comment by kmcquade** [comment]
For others reading this - #8 introduced the capability to override Access Levels per-action as the database is being built. I didn't build one out for resource ARNs though.

**Comment by jsmartin** [comment]
Ok, glad I'm not missing something.  In case you're interested, there's 2985 actions that are not associated with resource types.  I'll be pushing this up through AWS Support to see if they can give a response.  I would love for us to be able to override resource types if AWS is not doing their part, I just want to dig in a bit deeper as to why they aren't providing it in the first place.

**Comment by kmcquade** [comment]
> there's 2985 actions that are not associated with resource types... I would love for us to be able to override resource types if AWS is not doing their part

Chances are, those actions don't actually support resource ARN constraints. So even if resource ARNs do exist, it might not be possible to restrict the actions to those resources in IAM policies.

**Comment by jsmartin-r7** [comment]
Based on a support request and some back and forth they essentially responded "this is by design".  Which I interpret as "it takes effort to add ARN constraints to actions so we don't do them all".  Closing issue.

**Comment by jsmartin** [comment]
After some back and forth with support using an explicit example of an action that _could_ support ARNs but didn't, I was told "This is by design." Which I translate to "it requires development effort to limit actions to an ARN".  I figure unless  a bunch of people request for ARN restrictions for a specific action, they aren't going to implement.  Closing issue.
