### ISSUE TITLE
Creating multiple policies in the same folder using the Terraform module - please change template.json to unique names per call

### ISSUE THREAD

**Issue by jelledv** [salesforce/policy_sentry#334]
When you call the Terraform module multiple times, the local executor file "template.json" will be overwritten and you will get the same policy document for all the policies you want to create. 

This is my Terraform setup:
![image](https://user-images.githubusercontent.com/22740839/106447718-1e313700-6482-11eb-93a8-f287bd2a7d3d.png)

I would like to create a Terraform file per AWS service and call the module multiple times:
![image](https://user-images.githubusercontent.com/22740839/106448012-7a945680-6482-11eb-9f89-dd1f7cd9c475.png)

**Comment by kmcquade** [comment]
@jelledv - you might want to check out the Terraform provider! 

https://registry.terraform.io/providers/salesforce/policyguru/latest/docs

We'd love to get some feedback. We haven't promoted it very much, and we should probably update the documentation to reflect this. But that might solve your problem.

FYI @reetasingh

**Comment by kmcquade** [comment]
But since others are using the Terraform module already, you are correct that we should provide an option to set the file name, or make the file name based on something predictable and unique.
