### ISSUE TITLE
Find out a way to create IAM Policies with 1 terraform apply instead of 2

### ISSUE THREAD

**Issue by Shocktrooper** [salesforce/policy_sentry#340]
Currently the way it stands with the terraform module is that it is a tad troublesome having to do 2 terraform applies each time you want to create an IAM policy.  If we can figure out a way to do the whole process inside of a single terraform apply instead of 2 then it would greatly benefit end users of the module

**Comment by kmcquade** [comment]
@Shocktrooper - great point. We haven't publicized this much, but we do have a Terraform provider that you can use instead :) 

https://registry.terraform.io/providers/salesforce/policyguru/latest

**Comment by Shocktrooper** [comment]
Well I'll be @kmcquade this is even better than using the policy sentry module if it had 1 apply instead of 2.  Should we update the documentation for policy sentry to say you can use policyguru for policy generation.  On a slightly different note should the policy sentry terraform module be deprecated completely?  

Also are there functionality differences between the 2 that need to be reconciled E.G. it doesn't look like policyguru supports condition keys and such

**Comment by kmcquade** [comment]
@Shocktrooper - I think we should update the documentation, yes. We should leave the Terraform module for historical purposes and to avoid breaking anyone who uses it.

> PolicyGuru doesn't support condition keys 

Neither does Policy Sentry :) I added on some scaffolding to support that in the past and then abandoned it. The only consistent use case that I saw was ABAC/Tag-based AuthZ, but that would be frankly a PITA to maintain.

> Are there functionality differences between the two

PolicyGuru is basically Policy Sentry running as Lambda functions behind an API Gateway. You can view the Swagger docs here: https://api.policyguru.io/docs

We created this experimentally, so I can't say that it will be "production support." We open-sourced the code for this reason, and just in case anyone had reservations about sending their IAM policies to someone else's API gateway.

There are some format differences between the Terraform template and the Policy Sentry template. I took that opportunity to make the variable names longer, but a bit more self-explanatory. See the `actions_for_resources_at_access_level`, `actions_for_service_without_resource_constraint_support`, and `overrides` blocks.

```hcl
data "policyguru_document" "example" {
  actions_for_resources_at_access_level {
    write = list("arn:aws:kms:us-east-1:123456789012:key/aaaa-bbbb-cccc")
    read = list("arn:aws:s3:::mybucket")
  }

  actions_for_service_without_resource_constraint_support {
    list = list("s3")
    include_single_actions = ["ssm:GetParameter"]
  }

  overrides {
    skip_resource_constraints_for_actions = []
  }

  exclude_actions = list("kms:Decrypt*", "kms:Delete*", "kms:Schedule*")
}

resource "aws_iam_policy" "policy" {
  name        = "sample"
  path        = "/"
  description = "this uses policyguru document"
  policy      = data.policyguru_document.example.json
}
```

**Comment by kmcquade** [comment]
@Shocktrooper - I am going to close this. Feel free to update, re-open, or open a new one if you have any questions.
