### ISSUE TITLE
Minimize flag includes duplicate actions in the policy block

### ISSUE THREAD

**Issue by Shocktrooper** [salesforce/policy_sentry#364]
Summary
Currently as it stands using `--minimize` greatly reduces the amount of characters in an IAM policy but this can be improved even more for better clarity and even less characters in the resulting policy. 

Proposal
If you run certain policy generations with `--minimize` it results in a some action statement lists in a policy block that looks like the following

    "Sid": "RdsMultProjectname",
    "Effect": "Allow",
    "Action": [
        "rds:do*",
        "rds:l*",
        "rds:l*",
        "rds:l*",
        "rds:l*",
        "rds:l*",
        "rds:l*",
        "rds:l*",
        "rds:l*",
        "rds:l*",
        "rds:l*",
        "rds:l*",
        "rds:addt*",
        "rds:removet*",
        "rds:addt*",
        "rds:removet*",
        "rds:addt*",
        "rds:removet*",
        "rds:addt*",
        "rds:removet*",
        "rds:addt*",
        "rds:removet*",
        "rds:addt*",
        "rds:removet*",
        "rds:addt*",
        "rds:removet*",
        "rds:addt*",
        "rds:removet*",
        "rds:addt*",
        "rds:removet*",
        "rds:addt*",
        "rds:removet*",
        "rds:addt*",
        "rds:removet*",
        "rds:au*",
        "rds:modifydbclusters*",
        "rds:modifydbsnapshota*"
    ],
    "Resource": [
        "arn:aws:rds:*:*:*:${project_name}-*"
    ]

----
what we can do to improve the policy generation is do a loop through a single policy block before adding it to the resulting policy and filtering out action statements that are duplicates of one another.  This should greatly reduce the size of some policies and also improve the readability in the process as there not as many lines to go through in the resulting statement. After running the preceding policy block and removing the duplicates it should look like the following diagram

    "Sid": "RdsMultProjectname",
    "Effect": "Allow",
    "Action": [
        "rds:do*",
        "rds:l*",
        "rds:addt*",
        "rds:removet*",
        "rds:au*",
        "rds:modifydbclusters*",
        "rds:modifydbsnapshota*"
    ],
    "Resource": [
        "arn:aws:rds:*:*:*:${project_name}-*"
    ]

**Comment by kmcquade** [comment]
That does sound like it would be super helpful!

I actually borrowed the expansion logic from [Netflix-Skunkworks/policyuniverse](https://github.com/Netflix-Skunkworks/policyuniverse/blob/master/policyuniverse/expander_minimizer.py)

But I think the errors you mentioned happen in the minimize code [here](https://github.com/salesforce/policy_sentry/blob/master/policy_sentry/writing/minimize.py#L126) - outside of the logic that I borrowed from policyuniverse.

We should add some logic to https://github.com/salesforce/policy_sentry/blob/master/policy_sentry/writing/minimize.py#L125-L128 that removes duplicates.

@Shocktrooper you mentioned that this happens if you run "certain policy generations." Can you provide some example template files where you run into this problem? We can use those for our unit tests to verify that it fixes this issue.

**Comment by kmcquade** [comment]
Started looking at this again. I think this bug was introduced in https://github.com/salesforce/policy_sentry/pull/252, and not in the minimize.py file.

**Comment by kmcquade** [comment]
Making a PR for this shortly. Given the input shown below, this reduces the previously ridiculous output to the output shown below.

### Input

```yaml
mode: crud
name: 'test-policy-template'
read:
- 'arn:aws:rds:*:*:*:test-*'
write:
- 'arn:aws:rds:*:*:*:test-*'
list:
- 'arn:aws:rds:*:*:*:test-*'
tagging:
- 'arn:aws:rds:*:*:*:test-*'
permissions-management:
- 'arn:aws:rds:*:*:*:test-*'

```

### Output

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "RdsMultTest",
            "Effect": "Allow",
            "Action": [
                "rds:addroletodbc*",
                "rds:addroletodbi*",
                "rds:adds*",
                "rds:addt*",
                "rds:ap*",
                "rds:au*",
                "rds:b*",
                "rds:copydbclusterp*",
                "rds:copydbclusters*",
                "rds:copydbp*",
                "rds:copydbs*",
                "rds:copyo*",
                "rds:createcustomd*",
                "rds:createdbcluster",
                "rds:createdbclustere*",
                "rds:createdbclusterp*",
                "rds:createdbclusters*",
                "rds:createdbi*",
                "rds:createdbinstance",
                "rds:createdbpa*",
                "rds:createdbproxye*",
                "rds:createdbse*",
                "rds:createdbsn*",
                "rds:createdbsu*",
                "rds:createe*",
                "rds:createg*",
                "rds:createo*",
                "rds:deletecustomd*",
                "rds:deletedbcluster",
                "rds:deletedbclustere*",
                "rds:deletedbclusterp*",
                "rds:deletedbclusters*",
                "rds:deletedbinstance",
                "rds:deletedbpa*",
                "rds:deletedbproxy",
                "rds:deletedbproxye*",
                "rds:deletedbse*",
                "rds:deletedbsn*",
                "rds:deletedbsu*",
                "rds:deletee*",
                "rds:deleteg*",
                "rds:deleteo*",
                "rds:der*",
                "rds:describedbclusterb*",
                "rds:describedbclustere*",
                "rds:describedbclusterp*",
                "rds:describedbclusters",
                "rds:describedbclustersn*",
                "rds:describedbi*",
                "rds:describedbl*",
                "rds:describedbpa*",
                "rds:describedbpr*",
                "rds:describedbproxye*",
                "rds:describedbproxytargets",
                "rds:describedbse*",
                "rds:describedbsn*",
                "rds:describedbsnapshots",
                "rds:describedbsu*",
                "rds:describeeventsu*",
                "rds:describeg*",
                "rds:describeop*",
                "rds:describep*",
                "rds:describereserveddbinstances",
                "rds:describev*",
                "rds:do*",
                "rds:f*",
                "rds:failoverg*",
                "rds:l*",
                "rds:modifycur*",
                "rds:modifycus*",
                "rds:modifydbcluster",
                "rds:modifydbclustere*",
                "rds:modifydbclusterp*",
                "rds:modifydbclusters*",
                "rds:modifydbi*",
                "rds:modifydbpa*",
                "rds:modifydbproxy",
                "rds:modifydbproxye*",
                "rds:modifydbproxyt*",
                "rds:modifydbsnapshot",
                "rds:modifydbsnapshota*",
                "rds:modifydbsu*",
                "rds:modifye*",
                "rds:modifyg*",
                "rds:modifyo*",
                "rds:promotereadreplica",
                "rds:promotereadreplicad*",
                "rds:pu*",
                "rds:rebootdbc*",
                "rds:rebootdbi*",
                "rds:reg*",
                "rds:removef*",
                "rds:removerolefromdbc*",
                "rds:removerolefromdbi*",
                "rds:removes*",
                "rds:removet*",
                "rds:resetdbc*",
                "rds:resetdbp*",
                "rds:rest*",
                "rds:restoredbc*",
                "rds:restoredbclusterfromsn*",
                "rds:restoredbi*",
                "rds:restoredbinstancefromd*",
                "rds:rev*",
                "rds:starta*",
                "rds:startdbc*",
                "rds:startdbi*",
                "rds:stopa*",
                "rds:stopdbc*",
                "rds:stopdbi*"
            ],
            "Resource": [
                "arn:aws:rds:*:*:*:test-*"
            ]
        },
        {
            "Sid": "MultMultNone",
            "Effect": "Allow",
            "Action": [
                "iam:createservicel*",
                "iam:pa*",
                "mediaimport:c*",
                "rds:addt*",
                "rds:createdbinstance",
                "rds:deletedbinstance",
                "rds:modifydbi*",
                "rds:rebootdbi*"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```
