### ISSUE TITLE
APIGatewayV2 isn't included in the datastore

### ISSUE THREAD

**Issue by ethpran** [salesforce/policy_sentry#387]
I am using version `0.11.19`. While I see that the HTML for [amazonapigatewaymanagementv2](https://github.com/salesforce/policy_sentry/blob/0.11.19/policy_sentry/shared/data/docs/list_amazonapigatewaymanagementv2.html) exists in the repo, It looks like it's not making it to the datastore for some reason. I see that `apigateway` is mapped to an object with https://docs.aws.amazon.com/service-authorization/latest/reference/list_manageamazonapigateway.html. Maybe they're colliding?

**Comment by ethpran** [comment]
Actually, I'm not sure if it's not getting to the DB because I see `GET`, `POST`, etc... But what is missing I think are the correct resources. This is what I have:
```
  "resources": {
    "apigateway-general": {
      "resource": "apigateway-general",
      "arn": "arn:${Partition}:apigateway:${Region}::${ApiGatewayResourcePath}",
      "condition_keys": [
        "aws:ResourceTag/${TagKey}"
      ]
    }
  },

```
Even though [here](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonapigatewaymanagementv2.html#amazonapigatewaymanagementv2-resources-for-iam-policies) I see many others and `arn:${Partition}:apigateway:${Region}::${ApiGatewayResourcePath}` isn't anywhere to be found. What could be the cause of the discrepancy I'm seeing. I can't find anywhere on the web where this ARN exists in fact.

**Comment by ethpran** [comment]
I found it. It's this URL which is overriding the other configs: list_manageamazonapigateway.html. I'm not sure what this and why it's in the list, but after I removed it the DB looks like its created as expected, but still only with v2

**Comment by kmcquade** [comment]
Hey. I don’t have time to dig into it myself, but I would suggest running this script https://github.com/salesforce/policy_sentry/blob/master/utils/download_docs.py with the Python debugger on and set breakpoints for when the file is downloaded and throughout the aws_docs.py file. https://github.com/salesforce/policy_sentry/blob/master/policy_sentry/shared/awsdocs.py. That will probably help you discover the issue.

Are you sure they aren’t in the DB? Both of those HTML pages share the same IAM namespace (apigateway) which is definitely confusing. If it’s colliding I would definitely accept PRs to fix it though

**Comment by ethpran** [comment]
Thanks. Yeah I replicated it locally. I will try to put together a fix and
submit PR.
