### ISSUE TITLE
How to ignore "access-level-overrides.yml" file in python

### ISSUE THREAD

**Issue by Asma-Alhuwayil** [salesforce/policy_sentry#410]
I would prefer to query the database as it is from aws without any overrides.
But basically, while using Policy Sentry package with python, it's dynamically using to adjustment in this file **access-level-overrides.yml**. The question is, how to ignore it?

**Comment by kmcquade** [comment]
Try setting it to an empty file. or you could make a PR that allows one to override this with an environment variable instead. The place to make that override would be here.

https://github.com/salesforce/policy_sentry/blob/b6712c1bfee1eb0a34a0fa6e53e82f99d4f7d4a0/policy_sentry/shared/constants.py#L43

I am not making any updates to this package but would accept a PR in this case

**Comment by Asma-Alhuwayil** [comment]
> Try setting it to an empty file. or you could make a PR that allows one to override this with an environment variable instead. The place to make that override would be here.
> 
> https://github.com/salesforce/policy_sentry/blob/b6712c1bfee1eb0a34a0fa6e53e82f99d4f7d4a0/policy_sentry/shared/constants.py#L43
> 
> I am not making any updates to this package but would accept a PR in this case

Thanks for the suggestion. The change is ready but it seems i'm denied to create a PR, can you help?
