### ISSUE TITLE
resource-explorer-2 is not supported with function get_service_prefix_data

### ISSUE THREAD

**Issue by AmitNahMesh** [salesforce/policy_sentry#419]
Hey,
I'm using your API and it seems you are not supporting the resource-explorer-2 service, it's the new version of resource-explorer that exists in the configuration file iam_definition.json.

Can I override the iam_defenition.json file with my own file? If not can you please add support for this service?

Thank you in advanced, Amit!

**Comment by kmcquade** [comment]
Yes. Overriding the definition is covered in the documentation.
