### ISSUE TITLE
Shell completion not working?

### ISSUE THREAD

**Issue by yermulnik** [salesforce/policy_sentry#497]
Shell completion produces no shell completion code:
```shell
> which policy_sentry
/home/linuxbrew/.linuxbrew/bin/policy_sentry

> policy_sentry --version
policy_sentry, version 0.12.15

> $(_POLICY_SENTRY_COMPLETE=source policy_sentry)
# empty output
```
Is it only me?

**Comment by yermulnik** [comment]
Bump 🆙

**Comment by gruebel** [comment]
hey @yermulnik thanks for the reminder.

I checked and `click`'s latest major version changed the way auto complete works. I'll adjust the docs, but here is the way to do it now

for `bash`
```shell
eval "$(_POLICY_SENTRY_COMPLETE=bash_source policy_sentry)"
```

and for `zsh`
```shell
eval "$(_POLICY_SENTRY_COMPLETE=zsh_source policy_sentry)"
```

**Comment by yermulnik** [comment]
Thanks you. Can confirm it works with this change 👍🏻
